/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        sub: 'rgb(var(--color-sub) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        pane: 'rgb(var(--color-pane) / <alpha-value>)',
        surface: {
          canvas: 'rgb(var(--surface-canvas) / <alpha-value>)',
          card: 'rgb(var(--surface-card) / <alpha-value>)',
          pane: 'rgb(var(--surface-pane) / <alpha-value>)',
          subtle: 'rgb(var(--surface-subtle) / <alpha-value>)',
          muted: 'rgb(var(--surface-muted) / <alpha-value>)',
          strong: 'rgb(var(--surface-strong) / <alpha-value>)',
          disabled: 'rgb(var(--surface-disabled) / <alpha-value>)',
          interactive: 'rgb(var(--surface-interactive) / <alpha-value>)',
          'interactive-hover': 'rgb(var(--surface-interactive-hover) / <alpha-value>)',
          overlay: 'rgb(var(--surface-overlay) / <alpha-value>)',
        },
        content: {
          primary: 'rgb(var(--content-primary) / <alpha-value>)',
          strong: 'rgb(var(--content-strong) / <alpha-value>)',
          DEFAULT: 'rgb(var(--content-default) / <alpha-value>)',
          secondary: 'rgb(var(--content-secondary) / <alpha-value>)',
          muted: 'rgb(var(--content-muted) / <alpha-value>)',
          faint: 'rgb(var(--content-faint) / <alpha-value>)',
          disabled: 'rgb(var(--content-disabled) / <alpha-value>)',
          inverse: 'rgb(var(--content-inverse) / <alpha-value>)',
        },
        line: {
          subtle: 'rgb(var(--border-subtle) / <alpha-value>)',
          DEFAULT: 'rgb(var(--border-default) / <alpha-value>)',
          strong: 'rgb(var(--border-strong) / <alpha-value>)',
        },
        status: {
          error: 'rgb(var(--status-error) / <alpha-value>)',
          'error-strong': 'rgb(var(--status-error-strong) / <alpha-value>)',
          'error-surface': 'rgb(var(--status-error-surface) / <alpha-value>)',
          'error-border': 'rgb(var(--status-error-border) / <alpha-value>)',
          warning: 'rgb(var(--status-warning) / <alpha-value>)',
          'warning-surface': 'rgb(var(--status-warning-surface) / <alpha-value>)',
          'warning-border': 'rgb(var(--status-warning-border) / <alpha-value>)',
          success: 'rgb(var(--status-success) / <alpha-value>)',
          info: 'rgb(var(--status-info) / <alpha-value>)',
          unread: 'rgb(var(--status-unread) / <alpha-value>)',
        },
        selection: 'rgb(var(--selection-fill) / <alpha-value>)',
        link: 'rgb(var(--link-text) / <alpha-value>)',
        focus: 'rgb(var(--focus-ring) / <alpha-value>)',
        hp: {
          current: 'rgb(var(--hp-current) / <alpha-value>)',
          healed: 'rgb(var(--hp-healed) / <alpha-value>)',
          taken: 'rgb(var(--hp-damage-taken) / <alpha-value>)',
          track: 'rgb(var(--hp-track) / <alpha-value>)',
        },
        rarity: {
          common: 'rgb(var(--rarity-common) / <alpha-value>)',
          uncommon: 'rgb(var(--rarity-uncommon) / <alpha-value>)',
          elite: 'rgb(var(--rarity-elite) / <alpha-value>)',
          boss: 'rgb(var(--rarity-boss) / <alpha-value>)',
          mythic: 'rgb(var(--rarity-mythic) / <alpha-value>)',
          'super-rare': 'rgb(var(--rarity-super-rare) / <alpha-value>)',
        },
        notification: {
          normal: 'rgb(var(--notification-normal-text) / <alpha-value>)',
          rare: 'rgb(var(--notification-rare-text) / <alpha-value>)',
          surface: 'rgb(var(--notification-surface) / <alpha-value>)',
          border: 'rgb(var(--notification-border) / <alpha-value>)',
        },
      },
    },
  },
  plugins: [],
}
