import { spawnSync } from 'node:child_process';
import { cpSync, mkdtempSync, readFileSync, readdirSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
const repository = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const arg = (name, fallback) => process.argv.find(x => x.startsWith(`--${name}=`))?.slice(name.length+3) ?? fallback;
const source = resolve(arg('source', repository));
const mirror = mkdtempSync(join(tmpdir(), 'bokemo-api-performance-source-'));
for(const dir of ['src','desktop','public','sample_savedata']) cpSync(join(source,dir),join(mirror,dir),{recursive:true});
for(const entry of readdirSync(source,{withFileTypes:true})) if(entry.isFile()&&!entry.name.startsWith('.env')) cpSync(join(source,entry.name),join(mirror,entry.name));
symlinkSync(join(repository,'node_modules'),join(mirror,'node_modules'),'dir');
const matrix=readFileSync(join(repository,'tests/support/apiV1ConformanceMatrix.profile.ts'),'utf8');
const fixtureSource=`import assert from 'node:assert/strict';\nimport { getItemById } from '../../src/data/items';\nimport { createFreshGameState } from '../../src/hooks/useGameState';\nimport { serializeGameState } from '../../src/game/saveCodec';\nimport { encodeStoredStateSync as encodePersistedState } from '../../src/game/storageCompression';\nimport type { GameState } from '../../src/types';\nconst t0=Date.UTC(2030,0,1);\n`+matrix.slice(matrix.indexOf('function matrixSave('),matrix.indexOf('const defaultSavePayload'))+matrix.slice(matrix.indexOf('/** The first party has met'),matrix.indexOf('// ---------------------------------------------------------------------------------------------------------------------\n// One application'))+matrix.slice(matrix.indexOf('interface Actor {'),matrix.indexOf('/** Operations whose cells'))+`\nexport { matrixSave, encodeSave, commitFixtures, readFixtures, getItemById };\n`;
const recipeDir=join(mirror,'tests/support');
cpSync(join(repository,'tests/support'),recipeDir,{recursive:true});
const recipePath=join(recipeDir,'apiV1PerformanceRecipes.ts');writeFileSync(recipePath,fixtureSource);
await build({entryPoints:[recipePath],outfile:join(mirror,'recipes.cjs'),bundle:true,platform:'node',format:'cjs',define:{'import.meta.env.DEV':'false','import.meta.env.BASE_URL':'"/"',__APP_VERSION__:JSON.stringify(JSON.parse(readFileSync(join(source,'package.json'),'utf8')).version),__BUILD_NUMBER__:'0',__PUBLIC_CHARACTER_IMAGE_FILES__:'[]',__PUBLIC_CHIBI_IMAGE_FILES__:'[]',__AUTO_EQUIPMENT_PROFILE_ENABLED__:'false',__AFK_LIVE_PROFILE_ENABLED__:'false',__AFK_LIVE_PROFILE_FIXTURE__:'""',__RUNTIME_DIAGNOSTICS_DEFAULT_ENABLED__:'false'},plugins:[{name:'raw',setup(b){b.onResolve({filter:/\.md\?raw$/},a=>({path:resolve(a.resolveDir,a.path.slice(0,-4)),namespace:'raw'}));b.onLoad({filter:/.*/,namespace:'raw'},a=>({contents:`export default ${JSON.stringify(readFileSync(a.path,'utf8'))}`,loader:'js'}));}}],logLevel:'silent'});
writeFileSync(join(mirror,'src/api/v1/benchmarkDiagnostic.ts'),`import { resetBattleSeedSourceForTesting } from '../../game/battleSeedSource';\nimport { getProductionBattleTelemetry, resetProductionBattleTelemetryForTesting } from '../../game/battle';\nimport { getBattleKernelAbiVersion, getBattleKernelMemoryBytes } from '../../game/battleKernel';\nexport const fixedNow=Date.UTC(2030,0,1);\nexport function resetSeed(){resetProductionBattleTelemetryForTesting();let cursor=0n;resetBattleSeedSourceForTesting(()=> (0xaf123456n<<32n)|cursor++);}\nexport function stopSeed(){resetBattleSeedSourceForTesting(null);}\nexport const telemetry=()=>({...getProductionBattleTelemetry(),abiVersion:getBattleKernelAbiVersion(),wasmMemoryBytes:getBattleKernelMemoryBytes()});\n`);
const home=join(mirror,'src/components/HomeScreen.tsx');let s=readFileSync(home,'utf8');
s=`import { fixedNow, resetSeed, stopSeed, telemetry } from '../api/v1/benchmarkDiagnostic';\nimport { serializeGameState as benchmarkSerialize } from '../game/saveCodec';\n`+s;
s=s.replaceAll('        now: () => Date.now(),','        now: () => fixedNow,');
s=s.replace('  applicationApiRef.current.syncIdleState(state);',`  Object.assign(window,{__BOKEMO_API_BENCHMARK__:{resetSeed,stopSeed,telemetry,snapshot:()=>({state:benchmarkSerialize(applicationApiRef.current!.authority.getSnapshot().state),control:applicationApiRef.current!.authority.getSnapshot().control})}});\n  applicationApiRef.current.syncIdleState(state);`);
s=s.replace('      delivery: { send: sendApiV1Delivery },',`      delivery: { send: async (record) => { const url=(window as unknown as {__BENCHMARK_DELIVERY_URL__:string}).__BENCHMARK_DELIVERY_URL__; if(!url) return {kind:'failed',message:'isolated benchmark delivery URL unavailable'}; await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:record.id})}); return {kind:'delivered'}; } },`);
writeFileSync(home,s);
const gameplayPath=join(mirror,'src/hooks/useGameState.ts');const gameplay=readFileSync(gameplayPath,'utf8');writeFileSync(gameplayPath,gameplay.replace('const seed = new Uint32Array(1); crypto.getRandomValues(seed);','const seed = new Uint32Array(1); seed[0] = 0x5eed1234;'));

if(process.argv.includes('--party-profile')){
 const profile=`type Metrics=Record<string,{calls:number,ms:number}>;let metrics:Metrics={};export function take(){const result=metrics;metrics={};return result;}function add(name:string,ms:number){const e=metrics[name]??={calls:0,ms:0};e.calls++;e.ms+=ms;}export function sync<T>(name:string,task:()=>T):T{const t=performance.now();try{return task();}finally{add(name,performance.now()-t);}}export async function asyncMeasure<T>(name:string,task:()=>Promise<T>):Promise<T>{const t=performance.now();try{return await task();}finally{add(name,performance.now()-t);}}`;
 writeFileSync(join(mirror,'src/api/v1/partyBenchmarkProfile.ts'),profile);
 const authority=join(mirror,'src/api/v1/authority.ts');let a=readFileSync(authority,'utf8');a="import { sync as partyMeasure } from './partyBenchmarkProfile';\n"+a;a=a.replace('const stateChanged = !apiValuesEqual(serializeGameState(outcome.state), serializeGameState(input.state));',"const stateChanged = partyMeasure('authority.changeDetection',()=>!apiValuesEqual(serializeGameState(outcome.state), serializeGameState(input.state)));");writeFileSync(authority,a);
 const application=join(mirror,'src/api/v1/applicationApi.ts');let b=readFileSync(application,'utf8');b="import { sync as partySync, asyncMeasure as partyAsync } from './partyBenchmarkProfile';\n"+b;const accountEncoder=b.includes('await encodeApiAccountState(')?'encodeApiAccountState':'encodeStoredState';b=b.replace('await encodeApiAccountState(JSON.stringify(serializeGameState(snapshot)))','await encodeStoredState(JSON.stringify(serializeGameState(snapshot)))');b=b.replace('const savePayload = stateChanged || !accountSaveReusable ? await encodeStoredState(JSON.stringify(serializeGameState(snapshot))) : null;',"const savePayload = stateChanged || !accountSaveReusable ? await partyAsync('save.encoding',()=>encodeStoredState(partySync('save.serialization',()=>JSON.stringify(serializeGameState(snapshot))))) : null;");b=b.replace('await ports.session.accounts.commit(identity, savePayload, control as DesktopApiControlMetadata);',"await partyAsync('account.IPCCommit',()=>ports.session.accounts.commit(identity, savePayload, control as DesktopApiControlMetadata));");b=b.replace("()=>encodeStoredState(partySync('save.serialization'","()=>"+accountEncoder+"(partySync('save.serialization'");writeFileSync(application,b);
 const reads=join(mirror,'src/api/v1/readModels.ts');let c=readFileSync(reads,'utf8');c="import { asyncMeasure as partyAsync } from './partyBenchmarkProfile';\n"+c;c=c.replace('export async function buildApiV1ReadData(','async function buildApiV1ReadDataUnprofiled(');c+="\nexport const buildApiV1ReadData=(...args:Parameters<typeof buildApiV1ReadDataUnprofiled>):ReturnType<typeof buildApiV1ReadDataUnprofiled>=>partyAsync('read.projection',()=>buildApiV1ReadDataUnprofiled(...args));\n";writeFileSync(reads,c);
 writeFileSync(home,"import { sync as measurePartyControl } from '../api/v1/partyBenchmarkProfile';\nimport { take as takePartyTimings } from '../api/v1/partyBenchmarkProfile';\n"+readFileSync(home,'utf8').replace('serializeApiV1Control(control)',"measurePartyControl('control.serialization',()=>serializeApiV1Control(control))").replace('  applicationApiRef.current.syncIdleState(state);',"  Object.assign(window,{__PARTY_TIMINGS__:{take:takePartyTimings}});\n  applicationApiRef.current.syncIdleState(state);"));
}

cpSync(join(repository,process.argv.includes('--party-throughput')?'tests/performance/apiV1PartyThroughputDesktop.cjs':'tests/performance/apiV1BenchmarkDesktop.cjs'),join(mirror,'benchmark.cjs'));
const sourceVersion=JSON.parse(readFileSync(join(source,'package.json'),'utf8')).version;
const built=spawnSync(join(repository,'node_modules/.bin/vite'),['build'],{cwd:mirror,env:{...process.env,npm_package_version:sourceVersion},encoding:'utf8',maxBuffer:32*1024*1024});
writeFileSync(join(mirror,'build.log'),built.stdout+built.stderr);if(built.status!==0)throw new Error(built.stderr||built.stdout);
const output=resolve(arg('output',join(mirror,'report.json')));const environment=arg('environment','prod');
const env={...process.env,BOKEMO_BENCHMARK_OUTPUT:output,BOKEMO_PARTY_SEED:arg('seed',''),BOKEMO_PARTY_READS:arg('reads','1000'),BOKEMO_PARTY_CYCLES:arg('cycles','100'),BOKEMO_PARTY_NOOPS:arg('noops','1000'),BOKEMO_PARTY_REPLAYS:arg('replays','1000'),BOKEMO_BENCHMARK_SAMPLES:arg('samples','3'),BOKEMO_BENCHMARK_WARMUPS:arg('warmups','1'),BOKEMO_BENCHMARK_ONLY:arg('only',''),BOKEMO_BENCHMARK_FIXTURES:arg('fixtures','fresh'),BOKEMO_BENCHMARK_HEAVY:process.argv.includes('--heavy')?'1':'0',BOKEMO_BENCHMARK_ENVIRONMENT:environment,BOKEMO_BENCHMARK_SOURCE:source,BOKEMO_BENCHMARK_MIRROR:mirror};
console.log(JSON.stringify({mirror,output,environment,source}));
const result=spawnSync(join(repository,'node_modules/.bin/electron'),[join(mirror,'benchmark.cjs'),`--environment=${environment}`],{cwd:mirror,env,stdio:'inherit'});process.exitCode=result.status??1;
