import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';
import { ENEMIES } from '../../src/data/enemies.ts';
import { createBattleSeed, formatBattleSeed, runBattle } from '../../src/game/battleEngine.ts';
import { executeBattle, executeBattleWithSeed, getProductionBattleTelemetry, resetProductionBattleTelemetryForTesting } from '../../src/game/battle.ts';
import { beginBattleKernelMeasurement, endBattleKernelMeasurement } from '../../src/game/battleKernel.ts';
import { createWebCryptoBattleSeedForTesting, withBattleSeedSourceForTesting } from '../../src/game/battleSeedSource.ts';
import { hydrateGameState, serializeGameState } from '../../src/game/saveCodec.ts';
import { decodePersistedState } from '../../src/game/storageCompression.ts';
import type { GameState } from '../../src/types/index.ts';

function fixture() {
  const path = resolve(process.cwd(), 'sample_savedata/ALL_Exp8_v0.9.3_dev_20260816.kemoz');
  const envelope = JSON.parse(readFileSync(path, 'utf8')) as { saveDataCompressed: string };
  const state = hydrateGameState(JSON.parse(decodePersistedState(envelope.saveDataCompressed)) as GameState);
  const party = state.parties[0];
  const enemy = ENEMIES.find(entry => entry.id === 301);
  if (!party || !enemy) throw new Error('Missing seeded battle fixture');
  return { party, enemy, bags: state.bags, initialPartyHp: party.currentHp, state };
}

test('seeded battle entry point is reproducible and records replay metadata', () => {
  const input = fixture();
  const first = runBattle(input, 0x0123456789abcdefn);
  const second = runBattle(input, 0x0123456789abcdefn);
  assert.deepEqual(second, first);
  assert.equal(first.engineMetadata.protocolVersion, 3);
  assert.equal(first.engineMetadata.rngVersion, 1);
  assert.equal(first.engineMetadata.seedHex, '0123456789abcdef');
  assert.ok(first.engineMetadata.randomDrawCount > 0);
});

test('battle seeds are unsigned 64-bit values generated by Web Crypto', () => {
  assert.throws(() => formatBattleSeed(-1n), /unsigned 64-bit/);
  assert.throws(() => formatBattleSeed(0x1_0000_0000_0000_0000n), /unsigned 64-bit/);
  assert.equal(formatBattleSeed(0n), '0000000000000000');
  assert.equal(formatBattleSeed(0xffff_ffff_ffff_ffffn), 'ffffffffffffffff');
  const seed = createBattleSeed();
  assert.ok(seed >= 0n && seed <= 0xffff_ffff_ffff_ffffn);
});

test('production seed acquisition is one low/high Web Crypto call and failures are transactional', () => {
  let calls = 0;
  const seed = createWebCryptoBattleSeedForTesting({
    getRandomValues(values) {
      calls += 1;
      (values as Uint32Array)[0] = 0x89abcdef;
      (values as Uint32Array)[1] = 0x01234567;
      return values;
    },
  });
  assert.equal(calls, 1);
  assert.equal(seed, 0x0123456789abcdefn);
  assert.throws(() => createWebCryptoBattleSeedForTesting(undefined), /unavailable/);
  assert.throws(() => createWebCryptoBattleSeedForTesting({ getRandomValues() { throw new Error('crypto failure'); } }), /crypto failure/);

  const input = fixture();
  resetProductionBattleTelemetryForTesting();
  beginBattleKernelMeasurement();
  assert.throws(() => withBattleSeedSourceForTesting(() => { throw new Error('seed failure'); }, () => executeBattle(
    input.party, input.enemy, input.bags, input.initialPartyHp,
  )), /seed failure/);
  assert.equal(endBattleKernelMeasurement().calls, 0);
  assert.equal(getProductionBattleTelemetry().battles, 0);
});

test('seed boundaries, runtime types, and RNG versions are validated without wrapping', () => {
  const input = fixture();
  assert.doesNotThrow(() => executeBattleWithSeed(input.party, input.enemy, input.bags, 0n, 1, input.initialPartyHp));
  assert.doesNotThrow(() => executeBattleWithSeed(input.party, input.enemy, input.bags, 0xffff_ffff_ffff_ffffn, 1, input.initialPartyHp));
  assert.throws(() => executeBattleWithSeed(input.party, input.enemy, input.bags, -1n, 1, input.initialPartyHp), /unsigned 64-bit/);
  assert.throws(() => executeBattleWithSeed(input.party, input.enemy, input.bags, 0x1_0000_0000_0000_0000n, 1, input.initialPartyHp), /unsigned 64-bit/);
  assert.throws(() => executeBattleWithSeed(input.party, input.enemy, input.bags, 1 as never, 1, input.initialPartyHp), /bigint/);
  resetProductionBattleTelemetryForTesting();
  beginBattleKernelMeasurement();
  assert.throws(() => executeBattleWithSeed(input.party, input.enemy, input.bags, 1n, 2, input.initialPartyHp), /Unsupported battle RNG version/);
  assert.equal(endBattleKernelMeasurement().calls, 0);
  assert.equal(getProductionBattleTelemetry().battles, 0);
});

test('sequential explicit battles are isolated and failed execution cannot perturb replay', () => {
  const input = fixture();
  const first = runBattle(input, 11n);
  runBattle(input, 22n);
  const repeated = runBattle(input, 11n);
  assert.deepEqual(repeated, first);
  assert.throws(() => runBattle(input, -1n), /unsigned 64-bit/);
  assert.deepEqual(runBattle(input, 11n), first);
});

test('completed replay metadata survives save hydration and legacy logs remain valid', () => {
  const state = fixture().state;
  const party = state.parties[0]!;
  const log = party.lastExpeditionLog;
  assert.ok(log?.entries[0], 'sample save must retain one battle log entry');
  log.entries[0].replayMetadata = { protocolVersion: 3, abiVersion: 8, rngVersion: 1, seedHex: '0123456789abcdef', randomDrawCount: 42 };
  const hydrated = hydrateGameState(structuredClone(serializeGameState(state)));
  assert.deepEqual(hydrated.parties[0]!.lastExpeditionLog!.entries[0]!.replayMetadata, log.entries[0].replayMetadata);
  delete hydrated.parties[0]!.lastExpeditionLog!.entries[0]!.replayMetadata;
  assert.doesNotThrow(() => hydrateGameState(structuredClone(hydrated)));
});
