import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';
import { ENEMIES } from '../../src/data/enemies.ts';
import { createBattleSeed, formatBattleSeed, runBattle } from '../../src/game/battleEngine.ts';
import { hydrateGameState } from '../../src/game/saveCodec.ts';
import { decodePersistedState } from '../../src/game/storageCompression.ts';
import type { GameState } from '../../src/types/index.ts';

function fixture() {
  const path = resolve(process.cwd(), 'sample_savedata/ALL_Exp8_v0.9.3_dev_20260816.kemoz');
  const envelope = JSON.parse(readFileSync(path, 'utf8')) as { saveDataCompressed: string };
  const state = hydrateGameState(JSON.parse(decodePersistedState(envelope.saveDataCompressed)) as GameState);
  const party = state.parties[0];
  const enemy = ENEMIES.find(entry => entry.id === 301);
  if (!party || !enemy) throw new Error('Missing seeded battle fixture');
  return { party, enemy, bags: state.bags, initialPartyHp: party.currentHp };
}

test('seeded battle entry point is reproducible and records replay metadata', () => {
  const input = fixture();
  const first = runBattle(input, 0x0123456789abcdefn);
  const second = runBattle(input, 0x0123456789abcdefn);
  assert.deepEqual(second, first);
  assert.equal(first.engineMetadata.protocolVersion, 2);
  assert.equal(first.engineMetadata.rngVersion, 1);
  assert.equal(first.engineMetadata.seedHex, '0123456789abcdef');
  assert.ok(first.engineMetadata.randomDrawCount > 0);
});

test('battle seeds are unsigned 64-bit values generated by Web Crypto', () => {
  assert.equal(formatBattleSeed(-1n), 'ffffffffffffffff');
  const seed = createBattleSeed();
  assert.ok(seed >= 0n && seed <= 0xffff_ffff_ffff_ffffn);
});
