import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const inputPath = path.join(root, 'Specification_flavor_text.md');
const outputPath = path.join(root, 'src/data/flavorTextRuntime.ts');

const spec = fs.readFileSync(inputPath, 'utf8');
const lines = spec.split('\n');

const rows = [];
for (const line of lines) {
  if (!line.trim().startsWith('|')) continue;
  const cells = line.split('|').map((c) => c.trim());
  if (cells.length < 5) continue;
  const state = cells[1];
  const condition = cells[2];
  const text = cells[3];
  if (!state || state === 'state' || state === '-' || condition === '-' || text === '-') continue;
  rows.push({ state, condition, text });
}

const stateSet = [...new Set(rows.map((r) => r.state))];

function toClassId(label) {
  return label.toLowerCase();
}

function toRaceId(label) {
  return label.toLowerCase();
}

function parseCondition(raw) {
  const condition = raw.trim();
  if (condition === 'none') return { k: 'none' };

  const hpMatch = condition.match(/`d\.HP`\s*([<>])\s*(\d+)%\s*of\s*max\s*HP/i);
  if (hpMatch) {
    const op = hpMatch[1] === '>' ? 'hp_gt' : 'hp_lt';
    const value = Number(hpMatch[2]) / 100;
    return { k: op, v: value };
  }

  const classMatch = condition.match(/with\s+mainClass\.`([^`]+)`/i);
  if (classMatch) {
    return { k: 'class_is', v: toClassId(classMatch[1]) };
  }

  const raceMatch = condition.match(/with\s+race\.`([^`]+)`/i);
  if (raceMatch) {
    return { k: 'race_is', v: toRaceId(raceMatch[1]) };
  }

  return { k: 'raw', v: condition };
}

const conditions = [];
const conditionIdByKey = new Map();

function internCondition(parsed) {
  const key = JSON.stringify(parsed);
  const existing = conditionIdByKey.get(key);
  if (existing !== undefined) return existing;
  const id = conditions.length;
  conditions.push(parsed);
  conditionIdByKey.set(key, id);
  return id;
}

const stateIndex = new Map(stateSet.map((state, idx) => [state, idx]));
const entries = rows.map((row) => {
  const c = parseCondition(row.condition);
  const cId = internCondition(c);
  return [stateIndex.get(row.state), cId, row.text];
});

const out = `/* eslint-disable */\n// Generated by scripts/generateFlavorRuntime.mjs\n\nexport type FlavorCondition =\n  | { k: 'none' }\n  | { k: 'hp_gt'; v: number }\n  | { k: 'hp_lt'; v: number }\n  | { k: 'class_is'; v: string }\n  | { k: 'race_is'; v: string }\n  | { k: 'raw'; v: string };\n\nexport const FLAVOR_STATES = ${JSON.stringify(stateSet, null, 2)} as const;\n\nexport const FLAVOR_CONDITIONS: readonly FlavorCondition[] = ${JSON.stringify(conditions, null, 2)} as const;\n\nexport const FLAVOR_ENTRIES: ReadonlyArray<readonly [number, number, string]> = ${JSON.stringify(entries, null, 2)} as const;\n`;

fs.writeFileSync(outputPath, out);
console.log(`Generated ${outputPath} with ${entries.length} entries, ${conditions.length} condition kinds.`);
